language: php
php:
    - 7.2
    - 7.3
sudo: false
before_install:
    - composer self-update
    - composer install --no-interaction --prefer-dist --no-suggest
script:
    - vendor/bin/phpunit
notifications:
    email:
        on_success: never
        on_failure: always
